### ISSUE TITLE
support -w option for ARM CPU  / Apple Silicon

### ISSUE THREAD

**Issue by gmuth** [soulspace-org/overarch#2]
java -jar overarch.jar -w
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/g1/nqzzx5r95bl93qwm6pvq0jvw0000gn/T/jna9992242266778354184.tmp: dlopen(/private/var/folders/g1/nqzzx5r95bl93qwm6pvq0jvw0000gn/T/jna9992242266778354184.tmp, 0x0001): tried: '/private/var/folders/g1/nqzzx5r95bl93qwm6pvq0jvw0000gn/T/jna9992242266778354184.tmp' (fat file, but missing compatible architecture (have (unknown,i386,x86_64), need (arm64e)))
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
        at java.base/java.lang.Runtime.load0(Runtime.java:755)
        at java.base/java.lang.System.load(System.java:1953)
        at com.sun.jna.Native.loadNativeLibraryFromJar(Native.java:744)
        at com.sun.jna.Native.loadNativeLibrary(Native.java:678)
        at com.sun.jna.Native.<clinit>(Native.java:106)
        at com.barbarysoftware.jna.CarbonAPI.<clinit>(CarbonAPI.java:6)

There is a similar issue: https://clojurians-log.clojureverse.org/kaocha/2022-08-18
--> https://github.com/nextjournal/beholder

**Comment by lsolbach** [comment]
I will check, if beholder is a drop in replacement for hawk. If so, I'll replace hawk with beholder.

**Comment by lsolbach** [comment]
Switched from hawk to beholder and merged the change into the main branch. The change will be included in the next release 0.7.0.
